### ISSUE TITLE
Project Contribution by Francis

### ISSUE THREAD

**Issue by Muhammadzubair26** [zuri-training/Team_87_zuri_fetch_metadata#25]
Hi Francis, you were assigned the following tasks: Working on an empathy map, feature set, style guides, Hi-fi designs, and prototyping. Please outline how you went about your assignment, the issues you faced and how you went about resolving them

**Comment by FrancisEdu1** [comment]
> Hi Francis, you were assigned the following tasks: Working on an empathy map, feature set, style guides, Hi-fi designs, and prototyping. Please outline how you went about your assignment, the issues you faced and how you went about resolving them

- Empathy Map: with a great collaborative work from my teammates  I was able to draw an appropriate and effective THINK, SAY, FEEL and DO, which lead to a conclusive PAIN(s) and GAIN(s) of our user experience. 

- Feature Set: at first it gave me a hard time trying to figure out the actual features we will be needing for this platform. So we had to hold multiple team meeting, which was focused on understanding the project first. Everyone was in a rush to come up with something before the week runs out but the meeting was great help, not only to me but also to my fellow teammates. At last I was able to come up with some relevant features for our app with the help of my teammates. 

- Style Guide: there was too many styles and guides that need to be created so I had to take them one after the other, from the colors, typography, grids down to component sets. I also continued while we worked on different screens and pages and always created and dropped necessary  components on their style guide. 

- High Fidelity Designs: this time we realized we have a lot of screens to design so screens were shared and individuals worked on different screens. I worked on tablet and mobile screen for Landing Page,  helped fix up appearance and alignment of texts and objects on some other screens. 

-Prototyping: firstly we deployed the screens individually to developers after we were done with each, for fast paste. So we can cover more ground within a short period of time, but we discovered that some of them needed to see the screens flow pattern for an effective delivery from their end. So I prototyped the screens along side some team members which is still ongoing and should be done with soon.
