### ISSUE TITLE
Poject Contribution by Tranquil

### ISSUE THREAD

**Issue by Philbabb** [zuri-training/Team_87_zuri_fetch_metadata#32]
Tranquil is tasked with login page, extract metadata page, forgot/reset password pages and the form action pop-ups

**Comment by Tranquil068** [comment]
I handled the development of the login page and extract metadata page, Philip did the finishing of both pages.

**Comment by Tranquil068** [comment]
The form action pop-ups were developed by Victor, I did the finishing and CSS positioning of the icons and texts.

**Comment by Tranquil068** [comment]
I also developed the forgot and reset password pages, Victor did the finishing.
